project:
  pre-render: scripts/preRender.py
  post-render: scripts/postRender.py
  render:
    - index.qmd
    - "reports/*.qmd"
    # - reports/Anderson.qmd
    # - reports/dataSources.qmd
    # - reports/Blount.qmd
    # - reports/Campbell.qmd
    # - reports/Claiborne.qmd
  output-dir: docs
  type: website
profile:
  default: prod
website:
  navbar:
    background: primary
    search: true
    left:
      # - text: ETDD Census Data
      - index.qmd
      - reports/dataSources.qmd
      - text: "Counties"
        menu:
          - reports/Anderson.qmd
          - reports/Blount.qmd
          - reports/Campbell.qmd
          - reports/Claiborne.qmd
          - reports/Cocke.qmd
          - reports/Grainger.qmd
          - reports/Hamblen.qmd
          - reports/Jefferson.qmd
          - reports/Knox.qmd
          - reports/Loudon.qmd
          - reports/Monroe.qmd
          - reports/Morgan.qmd
          - reports/Roane.qmd
          - reports/Scott.qmd
          - reports/Sevier.qmd
          - reports/Union.qmd
          
#       - text: "Overview"
#         href: Overview.qmd
#       - text: "Data Description"
#         href: DataDescription.qmd 
bibliography: resources/references.bib
csl: common_shared_assets/citations/chicago-consistent-notes-intext-bibliography-access-dates.csl

logo:
  small: common_shared_assets/assets/ETDDLogo.svg
  medium: common_shared_assets/assets/ETDDLogo.svg
  
format: 
  dashboard:
    css: common_shared_assets/stylesheets/custom.css
    embed-resources: true   
    orientation: rows
    theme: [common_shared_assets/stylesheets/dashboardColorOne.scss,flatly]
    scrolling: true
    echo: false
    citations-hover: false
    footnotes-hover: false
    crossrefs-hover: false
  html:
    css: common_shared_assets/stylesheets/custom.css
    theme: [common_shared_assets/stylesheets/dashboardColorOne.scss, flatly]
    citations-hover: false
    footnotes-hover: false
    crossrefs-hover: false
    toc: true

    
execute: 
  cache: true
