---
title: "sampleCensusTables"
format: html
editor: source
---

```{r}
#| include: false
if (exists("startrun")) {
  print(fortunes::fortune())
} else {
  source(here::here("scripts","startHere.R"))
}

if (file.exists(here::here("data","clean","ods2010.csv"))) {
 empData2010 <- read_csv(here::here("data","clean","ods2010.csv"))
} else {
  source(here::here("scripts", "clean.R"))
  empData2010 <- read_csv(here::here("data","clean","ods2010.csv"))
}

source(here::here("scripts","defineColors.R"))



```


```{r}
totalJobs <- empData2010 |> 
  filter(workCountyName == "Anderson") |> 
  select(numberOfJobs) |> 
  summarize(sum(numberOfJobs)) |> 
  pull()

topFiveCounties <- empData2010 |> 
  filter(workCountyName == "Anderson") |> 
  # column_to_rownames(var="homeCountyName") |> 
  top_n(5) |> 
  select(homeCountyName) |> 
  pull()

empDataSubset <- empData2010 |> 
  filter(workCountyName == "Anderson") |> 
  mutate(
    homeCountyName=ifelse(homeCountyName %in% topFiveCounties, homeCountyName, "All Other Locations"),
    ) |> 
  group_by(homeCountyName) |> 
  summarize(
    numberOfJobs=sum(numberOfJobs),
    percentageOfJobs=numberOfJobs/totalJobs
    ) |> 
  ungroup() |> 
  mutate(isNotOther = ifelse(homeCountyName == "All Other Locations",0,1)) |> 
  arrange(desc(isNotOther),desc(numberOfJobs) ) |> 
    select(-isNotOther)
  
  
```

```{r}
empDataSubset |> 
  # gt() |>
    gt(rowname_col = "homeCountyName") |>
   grand_summary_rows(
    columns=numberOfJobs,
    fns = 
      list(label = "Total In-Commuting Jobs", fn = "sum")
    ,
    fmt = ~ fmt_number(., use_seps = TRUE, decimals = 0)  
    ) |> 
  grand_summary_rows(
     columns=percentageOfJobs,
    fns = list(
      list(label = "Total In-Commuting Jobs", fn = "sum")
    ),
    fmt = ~ fmt_percent(., decimals = 0)
    ) |> 
  fmt_percent(
    columns = percentageOfJobs
  ) |> 
  fmt_number(
    columns = numberOfJobs,
    decimals = 0
  ) |> 
   tab_header(
    title = "IN-COMMUTING JOB COUNTS:
\nANDERSON COUNTY LABORERS
\nBY COUNTIES WHERE LABORERS RESIDE"
  ) |> 
    tab_options(
      heading.background.color = etddBlue,
      column_labels.background.color = etddBlue
    ) |> 
  
  tab_style(
    style = list(
      cell_borders(sides = "all", color = borderColor, weight = px(3))
    ),
    locations = list(
      cells_body(
      # entire column
      columns = everything()
    ),
    cells_column_labels()
  )
  ) |> 
  tab_style(style = cell_fill(color = lightStripe),
            locations = cells_body(rows = c(1, 3, 5))) |> 
  tab_style(style = cell_fill(color = medStripe),
            locations = cells_body(rows = c(2, 4, 6))) |> 
  tab_style(style = cell_fill(color = medStripe),
            locations = cells_grand_summary()
  ) |> 
  tab_style(
      style = list(
        cell_fill(color = etddBlue),
        cell_text(color = colorForTextOnETDDBlue)
      ),
      # fn=function(x) !is.na(x),
      locations = list(cells_stub(), cells_stub_grand_summary()) # cells_body(columns = homeCountyName),
      # extents = "stub"
  )|>
   cols_label(
    numberOfJobs = "Job Count",
    percentageOfJobs = "Percentage",
    homeCountyName="Laborer’s County of Residence"
  )

```


  tab_spanner(
    label = "Car Info",
    columns = vars(year, bdy_style, trim)
  )


# Resources
https://lehd.ces.census.gov/data/lodes/LODES8/LODESTechDoc8.4.pdf

https://themockup.blog/static/resources/gt-cookbook.html#create-or-modify-parts