tidyCensusCite <- "Kyle Walker and Matt Herman"
ipumsrCite <- "Greg Freedman Ellis et al."
ACS_2020Cite <- "U. S. Census Bureau"
ACS_2010Cite <- "U. S. Census Bureau"
Census_2020Cite <- "U. S. Census Bureau"
Census_2010Cite <- "U. S. Census Bureau"
lodesCite <- "U. S. Census Bureau"
tigerFilesCite <- "U. S. Census Bureau"
AITrainingCopyright2025Cite <- "United States Copyright Office"
AICopyright2025Cite <- "United States Copyright Office"
llmNotAGICite <- "Dwarkesh Patel"
aiScaling2024Cite <- ""
elizaEffectCite <- "Dave Bergmann"
attentionAllYouNeedCite <- "Ashish Vaswani et al."
gpuForAICite <- ""
aiRMFCite <- "Elham Tabassi"
teslersTheoremCite <- ""
sepCite <- ""
Chan_2025Cite <- "Cecilia Ka Yuk Chan"
Chugani_2025Cite <- "Vinod Chugani"
sanJoseAICite <- "City of San José’s Information Technology Department: Digital Privacy Office"
Freestone_2026Cite <- "Tim Freestone"
Klein_2026Cite <- "Offer Klein"
Namco_2024Cite <- "Namco"
Pasquini_2025Cite <- "Brian Kennedy Pasquini Colleen McClain and Giancarlo"
copilotBugConfidentialCite <- "Craig Hale published"
Romeo_Conti_2026Cite <- "Giuseppe Romeo and Daniela Conti"
Tabassi_2023Cite <- "Elham Tabassi"
nvidiaCodeExecutionCite <- ""
AIVideoGamesCite <- ""
wiretapCite <- ""
otterLegalCite <- ""
spamCite <- ""
genAIVsOtherCite <- ""
sunkCostCite <- ""
owaspLLMCite <- ""
owaspBlindTrustCite <- ""
spellCheckAICite <- "CLRN team"
grammarAICite <- ""
mozillaTransparancyCite <- ""
foundationModelIndexCite <- ""
Explained_2025Cite <- ""
mitAIPolicyBriefsCite <- ""
regOf2025For2026Cite <- ""
genAICodeCybersecurityCite <- ""
owaspAICite <- ""
stanfordAILitCite <- ""
tensorflowMLCite <- ""
Rudko_Bashirpour_Bonab_2025Cite <- "Ihor Rudko and Aysan Bashirpour Bonab"
GabrielssonCite <- "Rickard Brüel Gabrielsson"
LLM_101_2025Cite <- ""
Brenndoerfer_2025Cite <- "Michael Brenndoerfer"
Russell_Norvig_2022Cite <- "Stuart J. Russell and Peter Norvig"
crashCourseAICite <- ""
